matrix:
  include:
  - os: linux
    python: 2.7
    env: PYTHON_VERSION=2.7
  - os: linux
    python: 3.3
    env: PYTHON_VERSION=3.3
  - os: linux
    python: 3.4
    env: PYTHON_VERSION=3.4
  - os: linux
    python: 3.5
    env: PYTHON_VERSION=3.5
  - os: osx
    language: generic
    env:
    - PYTHON_VERSION=2.7
  - os: osx
    language: generic
    env:
    - PYTHON_VERSION=3.3
  - os: osx
    language: generic
    env:
    - PYTHON_VERSION=3.4 
  - os: osx
    language: generic
    env:
    - PYTHON_VERSION=3.5

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda install --yes python=$PYTHON_VERSION
  - python --version

  # Download release distribution file
  - wget http://pages.cs.wisc.edu/~paulgc/py_stringmatching-0.1.0.tar.gz

  # Unzip file
  - tar -xvzf py_stringmatching-0.1.1.tar.gz

  # install package
  - cd py_stringmatching-0.1.1
  - python setup.py install

script:
  # test package
  - cd $HOME
  - pwd
  - ls
  - "python -c \"import py_stringmatching as sm; ed = sm.Levenshtein(); print(ed.get_raw_score('ab', 'at'))\""
