matrix:
  include:
  - os: linux
    python: 2.7
    env: PYTHON_VERSION=2.7
  - os: linux
    python: 3.3
    env: PYTHON_VERSION=3.3
  - os: linux
    python: 3.4
    env: PYTHON_VERSION=3.4
  - os: linux
    python: 3.5
    env: PYTHON_VERSION=3.5
  - os: osx
    language: generic
    env:
    - TOXENV=py27
    - PYTHON_VERSION=2.7
  - os: osx
    language: generic
    env:
    - TOXENV=py33
    - PYTHON_VERSION=3.3
  - os: osx
    language: generic
    env:
    - TOXENV=py34
    - PYTHON_VERSION=3.4 
  - os: osx
    language: generic
    env:
    - TOXENV=py35
    - PYTHON_VERSION=3.5

install:
  - python --version

  # Download release distribution file
  - wget http://pages.cs.wisc.edu/~paulgc/py_stringmatching-0.1.1.tar.gz

  # Unzip file
  - tar -xvzf py_stringmatching-0.1.1.tar.gz

  # install package
  - cd py_stringmatching-0.1.1
  - python setup.py install

script:
  # test package
  - cd $HOME
  - pwd
  - ls
  - "python -c \"import py_stringmatching as sm; ed = sm.Levenshtein(); print(ed.get_raw_score('ab', 'at'))\""
